import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {getSortedPostsData} from "../lib/post";
import {GetStaticProps} from "next";
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps: GetStaticProps = async () => {
    const allPostsData = getSortedPostsData();
    return {
        props:{
            allPostsData
        }
    }
}
export default function Home({allPostsData} : {
    allPostsData: {
        date:string
        title:string
        id:string
    }[]
}) {
  return (
    <>
      <Head>
        <title>NextJs Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.main}>
        <h1>[Nabi-Yi Introduction]</h1>
        <h1> A Test Website</h1>
      </section>
      <section className={`${styles.card}`}>
        <h2>Posts</h2>
          <ul className={styles.card}>
              {allPostsData.map(({id, title, date}) =>
                  <li className = {styles.card} key={id}>
                      <Link href={`/posts/${id}`}>
                          {title}
                      </Link>
                      <br/>
                      <small className = {styles.content}>{date}</small>
                      <p></p>
                  </li>
              )}
          </ul>
      </section>

    </>
  )
}

